name: YOLO
server:
  cut-layer: a #or b, c, d
  clients:
    - 1
    - 1
  model: yolo11n
  batch-frame: 1
model: yolo11n
rabbit:
  address: "192.168.101.91"
  username: "dai"
  password: "dai"
  virtual-host: /
  queue_device_1: "device1"
  queue_device_2: "device2"

data: video.mp4
log-path: res
control-count: 10
debug-mode: False
compress:
  enable: False
  num_bit: 8
cal_map:
  enable: False
  create_label: False

time_layer:
  num_round: 2
  input_shape: [1, 3, 640, 640]

partition:
  auto: True        # if set False then get [server][cut-layer]
  re-measure: False # if set False then get result from cut_point.log

clustering :
  mode : False
  num_clusters : 2   # set 0 : find the best K value
  max_iterations: 500 # loop in k means core
  num_runs : 20       # loop for find the best silhouette value
  weights : [1.4 , 1.2 , 1.1 , 0.65]  # core , total ram , internet , storage respectively

