name: YOLO
server:
  cut-layer: b #or b, c, d
  clients:
    - 1
    - 1
  model: yolo11n
  batch-frame: 5
rabbit:
  address: "192.168.101.91"
  username: "dai"
  password: "dai"
  virtual-host: /

data: video.mp4
log-path: .
control-count: 10
debug-mode: False
compress:
  enable: True
  num_bit: 8
cal_map:
  enable: False
  create_label: False