name: YOLO
server:
  cut-layer: b #or b, c, d
  clients:
    - 1
    - 1
  model: yolo11n
  batch-frame: 2
model: yolo11n
rabbit:
#  address: 127.0.0.1
#  username: guest
#  password: guest
  address: "192.168.101.91"
  username: "dai"
  password: "dai"
  virtual-host: /
  queue_device_1: "device1"
  queue_device_2: "device2"

data: video.mp4
log-path: .
control-count: 10
debug-mode: False
compress:
  enable: True
  num_bit: 8
cal_map:
  enable: False
  create_label: False

time_layer:
  num_round: 2
  input_shape: [1, 3, 640, 640]

partition:
  auto: False       # if set False then get [server][cut-layer]
  re-measure: False # if set False then get result from partition.json
